services:
  backend:
    build:
      context: ./apigw
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./apigw:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontapp
      dockerfile: Dockerfile
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    volumes:
      - ./frontapp:/app
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000